---
- name: debug module demo
  hosts: all
  tasks:
    - name: debug message
      ansible.builtin.debug:
        msg: "{{ ansible_version }}"
        verbosity: 1
- name: ping module demo
  hosts: all
  tasks:
    - name: test connection
      ansible.builtin.ping:
- name: Transfer and execute a script.
  hosts: all
  user: ansible
  tasks:
    #https://www.baeldung.com/linux/ansible-add-user-password-groupmkpasswd --method=sha-512
    - name: Add user ansible
      user:
        name: ansible
        shell: /bin/sh
        createhome: yes # Defaults to yes
        home: /home/ansible # Defaults to /home/<username>

    - name: Create password for user ansible
      user:
        name: ansible
        password: $y$j9T$jw3An8oM5Rjygvat3TIYa0$O3bHlHRlCGHyNKeuXc7L9U2acLp1E7bgrT1s6DflO/7

    - name: Transfer the script
      copy: src=create_cluster.sh dest=/home/ansible mode=0777

    - name: Execute the script
      command: sh /home/ansible/create_cluster.sh
- name: Initialize master node.
  hosts: master
  user: ansible
  tasks:
    - name: Transfer the script
      copy: src=init_masternode.sh dest=/home/ansible mode=0777
    - name: Initize Master node
      command: sh /home/ansible/init_masternode.sh
    - fetch:
        src: /home/ansible/init-log.txt
        dest: ./init-log.txt
        flat: true

- name: Join worker components
  hosts: workers
  user: ansible
  tasks:
    - copy:
        src: ./init-log.txt
        dest: /home/ansible/init-log.txt
    - name: Transfer the script
      copy: src=join_workers.sh dest=/home/ansible mode=0777
    - name: Join workers
      command: sh /home/ansible/join_workers.sh
    - name: Transfer the script
      copy: src=pod-network.shh dest=/home/ansible mode=0777
- name: Install CNI
  hosts: master
  user: ansible
  tasks:
    - name: Transfer the script
      copy: src=pod-network.sh dest=/home/ansible mode=0777
    - name: Install CNI
      command: sh /home/ansible/pod-network.sh
