# Stack (deprecated) used to create the builder
[stack]
id = "heroku-22"
# This image is used at runtime
run-image = "swarntech/appship-run:ubuntu-22"
# This image is used at build-time
build-image = "swarntech/appship-build:ubuntu-22"

[lifecycle]
version = "0.19.6"

# Buildpacks to include in builder
[[buildpacks]]
uri = "samples/buildpacks/hello-processes"

[[buildpacks]]
uri = "samples/buildpacks/heroku-buildpack-go-189"

[[buildpacks]]
uri = "samples/buildpacks/heroku-buildpack-python-242"

# Order used for detection

[[order]]
    [[order.group]]
    id = "heroku/go"
    version = "0.0.1"

[[order]]
    [[order.group]]
    id = "heroku/python"
    version = "0.0.1"